import Head from 'next/head'
import React from 'react';
import { Button } from 'antd';
import MultilineText from '@/components/MultilineText';
import styles from '../styles/style.module.less';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>demo</a>
        </h1>
      </main>
      <Button>123</Button>
      <div style={{width:200, height: 44}}>
          <MultilineText tooltip row={2} text="这是一个很长很长的字这是一个很长很长的字这是一个很长很长的字这是一个很长很长的字"/>
        </div>
    </div>
  )
}
