import Head from 'next/head'
import styles from '../styles/style.module.less'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>demo</a>
        </h1>
      </main>
    </div>
  )
}
